activation: silu
aggr: add
atom_filter: -1
attn_activation: silu
batch_size: 80
coord_files: null
cutoff_lower: 0.0
cutoff_upper: 5.0
dataset: MD17A
dataset_arg: aspirin
dataset_root: /home/fengshikun/Backup/Denoising/data/md17
derivative: true
distance_influence: both
distributed_backend: ddp
early_stopping_patience: 300
ema_alpha_dy: 1.0
ema_alpha_y: 0.05
embed_files: null
embedding_dimension: 128
energy_files: null
energy_weight: 0.2
force_files: null
force_weight: 0.8
inference_batch_size: 64
load_model: null
log_dir: logs/
lr: 0.001
lr_factor: 0.8
lr_min: 1.0e-07
lr_patience: 30
lr_warmup_steps: 1000
max_num_neighbors: 32
max_z: 100
model: equivariant-transformer
neighbor_embedding: true
ngpus: -1
num_epochs: 3000
num_heads: 8
num_layers: 6
num_nodes: 1
num_rbf: 32
num_workers: 6
output_model: Scalar
precision: 32
prior_model: null
rbf_type: expnorm
redirect: false
reduce_op: add
save_interval: 10
splits: null
standardize: true
test_interval: 10
test_size: null
train_size: 9500
trainable_rbf: false
val_size: 500
weight_decay: 0.0
md17: true
seperate_noise: true
output_model_noise: VectorOutput
position_noise_scale: 0.005
dihedral_angle_noise_scale: 0.1
denoising_weight: 0.1
composition: true
layernorm_on_vec: null
wandb_notes: ""
job_id: auto
